[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "advent2024"
path = "src/main.rs"

[dependencies]
regex = "1.11"
rayon = "1.10"
nohash-hasher = "0.2"
