[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "aoc2024"
path = "src/bin/aoc2024.rs"

[dependencies]
regex = "1.11"
rayon = "1.10"
nohash-hasher = "0.2"
clap = { version = "4.5", features = ["derive"] }
